meta_title: "Kitepirinha - Trouvez facilement les meilleurs spots de kitesurf proche de vous"
meta_description: "Trouvez facilement le spot de kitesurf autour de vous le plus adapté aux conditions. Toutes les infos pratiques sans vous prendre la tête."
meta_image: "image_meta.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@jeromeburkard" # indispensable pour les Twitter Cards
